name: Draft Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v7
        with:
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
